# Generated by Django 6.0.2 on 2026-02-22 06:51

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Criminal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('middle_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('dob', models.DateField()),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('nationality', models.CharField(max_length=50)),
                ('education_level', models.CharField(max_length=40)),
                ('phone', models.CharField(max_length=15, null=True, validators=[django.core.validators.RegexValidator('^\\+?\\d{9,15}$')])),
                ('crime_type', models.CharField(max_length=30)),
                ('religion', models.CharField(max_length=15)),
                ('image', models.ImageField(upload_to='criminal_images/')),
                ('status', models.CharField(choices=[('jailed', 'Jailed'), ('released', 'Released')], default='jailed', max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('case_number', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('pending', 'Pending')], max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('attached_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases_attached', to=settings.AUTH_USER_MODEL)),
                ('attached_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='cases.criminal')),
            ],
        ),
    ]
