# Generated by Django 6.0.2 on 2026-03-09 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='criminal',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
