# Generated by Django 6.0.2 on 2026-03-09 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_criminal_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criminal',
            name='status',
            field=models.CharField(choices=[('wanted', 'Wanted'), ('under investigation', 'Under Investigation'), ('jailed', 'Jailed'), ('released', 'Released')], default='jailed', max_length=20),
        ),
    ]
